### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Tfausx** [crskycode/YuRis_Tool#1]
Hello,

Seeing the code, this tool seems to be compatible only with 渡り鳥のソムニウム visual novel, i tested with other games, but i get this error

![c](https://user-images.githubusercontent.com/29191836/160287097-50cc5580-0bd8-44f9-8a82-c0d71bb37983.png)

Also, the path of this tool it's with your windows user, in order to use it, people need to modify that.

**Comment by crskycode** [comment]
The tool is under development

**Comment by Cosetto** [comment]
> The tool is under development

Hello Crsky, can you add the Cxcrypt for Café Stella(Steam). I'd emailed you the game few days ago
